### ISSUE TITLE
Conform to Gleam's result convention.

### ISSUE THREAD

**Issue by lpil** [Michael-Mark-Edu/bravo#1]
Hello!

In all Gleam code `Result` is used to represent success and failure, while `Option` is only used for nullable parameters. This means that operations such as `dict.get` return results.

https://hexdocs.pm/gleam_stdlib/gleam/option.html

This library is not using the Gleam convention, which is surprising, results in additional overhead, and means programmers don't get warnings for accidentally discarded values. Would you consider adopting Gleam's conventions?

Thanks,
Louis

**Comment by Michael-Mark-Edu** [comment]
My first issue, and it comes from Louis Pilford himself!

I didn't even realize that use of `Option` as a return type was discouraged. I have experience with Rust (and even a little bit of Haskell from that one time I tried and failed to learn it) where afaik you can return `Option`s.

Thankfully, I'm pretty sure I use `Option` exclusively as a return type in this codebase, so it won't be hard to turn all of the `Option(x)`s into `Result(x, Nil)`s. Only issue with this is that this will be a breaking change, meaning the next update will be v4.0.0.

I'll definitely change this! Thanks for the feedback!

**Comment by Michael-Mark-Edu** [comment]
@lpil Before I make a release with the changes I made in 3d62967 are there any other potentially breaking changes that you'd suggest I make? I like bundling all of my breaking changes into singular updates to avoid the version number getting too big.
